# This is the yaml configuration file for dnsproxy with minimal working
# configuration, all the options available can be seen with ./dnsproxy --help.
# To use it within dnsproxy specify the --config-path=/<path-to-config.yaml>
# option.  Any other command-line options specified will override the values
# from the config file.
---
bootstrap:
  - 9.9.9.9:53
  - 1.1.1.1:53
listen-addrs:
  - 0.0.0.0
listen-ports:
  - 53
max-go-routines: 0
ratelimit: 0
udp-buf-size: 0
cache:
edns:
all-servers:
upstream:
  - tls://9.9.9.9
  - tls://149.112.112.112
fallback:
  - tls://1.1.1.1
  - tls://1.0.0.1