version: '3.3'
services:
	dnsproxy:
		environment:
			- 'CONFIG=-u=tls://9.9.9.9' 	# edit after CONFIG=
		ports:
			- '53:53/udp' 					# plain old DNS port
			- '53:53/tcp'					# plain old DNS over tcp
			# - '853:853'					# dns over tls INTO the container
			# - '443:443'					# dns over https INTO the container
		image: vmstan/dnsproxy